### ISSUE TITLE
no negative "pi" for autocorr?

### ISSUE THREAD

**Issue by pmcdonal** [cosmodesi/pycorr#9]
If, at least for certain settings, symmetry between positive and negative pi is guaranteed, it would be nice to be able to just call with that assumption... assuming it will not do that if I plug in no negative edges... (e.g., not sure how it decides positive and negative for autocorrelation with midpoint los).

**Comment by adematti** [comment]
Would you be fine with a wrap() method (or any other name that makes more sense to you), that would resum negative pi (or mu) onto positive ones? e.g.
`corr = TwoPointCorrelationFunction('rppi', edges=(np.linspace(0., 100., 51), np.linspace(-20., 20., 41)), ...).wrap()` would give the correlation function for (rp >= 0, pi >= 0) with edges `(np.linspace(0., 100., 51), np.linspace(0., 20., 21))`.

(I'd rather not add special cases on how edges are handled in TwoPointCorrelationFunction/TwoPointCounter depending on auto or cross-correlation or choice of line-of-sight).

To answer your question, no negative edges will (currently, to ensure backward-compatibility) be cast to symmetric edges (`np.linspace(-20., 20., 41)` above) while issuing a warning, and pair counts are totally symmetric for negative/positive pi in case of autocorrelation with midpoint line-of-sight -- except numerical rounding, or zero-separation pairs.

**Comment by adematti** [comment]
ok
exactly the same, except for pairs falling right onto a bin edge (pi/mu-binning being defined by pi falls in bin i if edges[i] <= pi < edges[i + 1], with first edge exclusive, though)
In case of autocorrelation, the loop goes through all unique i < j pairs, but these are binned twice, recomputing mu in case of firstpoint or endpoint line-of-sight. This takes a bit more time, but not twice as much since we're not looping through all pairs with associated distance calculation.
The wrap method should be implemented in 81b4774dcd168de56c6785e80b26e78d02c45aad. The code has been updated on NERSC.

**Comment by pmcdonal** [comment]
Ok, thanks. (The wrap() is still nice to avoid needing to figure out what to do about the fact that otherwise rpar=0 appears somewhere in the middle of the array... not that this is hard once you understand it, but everything is friction...)
